language: php
php:
    - "7.0"
    # - "5.3"
before_script:
    - composer install
    - npm -g install npm@next
    - npm install
    - npm -g install bower
    - bower install
script: phpunit --configuration phpunit.xml --coverage-text